default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: restreview_development
  # database: myapp_development
  # host: db
  # socket: /tmp/mysql.sock


test:
  <<: *default
  database: restreview_test
  # database: myapp_test
  # host: db
  # socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
